apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kaniko-pipeline-run
spec:
 serviceAccountName: tkn-sa
 pipelineRef:
   name: kaniko-pipeline # refer to the pipeline above
 params:
   - name: git_revision
     value: HEAD
 workspaces:
   - name: git-source
     volumeClaimTemplate: # create volume claim
       spec:
         accessModes:
           - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
         resources:
           requests:
             storage: 100m
