apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
spec:
 replicas: 3
 selector:
   matchLabels:
     app: web-app
 template:
   metadata:
     labels:
       app: web-app
   spec:                  
     containers:
     - name: web-app
       image: vigneshvicky12345/maven:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 80
