apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlweb
spec:
 replicas: 3
 selector:
   matchLabels:
     app: web-app
 template:
   metadata:
     labels:
       app: web-app
   spec:                  
     containers:
     - name: web-app
       image: vigneshvicky12345/maven:1d949758987929525ddeeb2226f13d535cd33930
       imagePullPolicy: Always
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: htmlweb-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 8087
      protocol: TCP
      targetPort: 80
